#!/bin/bash

ksnip_options="-fs"
ksnip_output_skip=23
if [[ $1 == "selection" ]]; then
  ksnip_options="-rs"
elif [[ $1 == "last-selection" ]]; then
  ksnip_options="-ls"
fi

ksnip_output="$(ksnip $ksnip_options)"

if [[ ! $ksnip_output ]]; then
  exit
fi

screenshot_file="$(echo "$ksnip_output" | dd bs=1 skip=$ksnip_output_skip status=none)"

if [[ $1 == "selection" ]]; then
  gpaste-client file "$screenshot_file" &
fi

thumbnail_file="$(thumbnail "$screenshot_file")"

action="$(notify-send \
  --app-name ksnip \
  --action default=Open \
  --action edit=Edit \
  --action copy=Copy \
  --icon "$thumbnail_file" \
  "Screenshot saved" "$screenshot_file")"

case $action in
default)
  xdg-open "$screenshot_file"
  ;;
edit)
  ksnip "$screenshot_file"
  ;;
copy)
  gpaste-client file "$screenshot_file"
  ;;
esac
